"""Add MarketData model

Revision ID: 0ddab6dfe89e
Revises: 
Create Date: 2025-07-05 15:22:44.128413

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ddab6dfe89e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=True),
    sa.Column('bid', sa.Float(), nullable=True),
    sa.Column('ask', sa.Float(), nullable=True),
    sa.Column('spread', sa.Float(), nullable=True),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.Column('bidhigh', sa.Float(), nullable=True),
    sa.Column('bidlow', sa.Float(), nullable=True),
    sa.Column('askhigh', sa.Float(), nullable=True),
    sa.Column('asklow', sa.Float(), nullable=True),
    sa.Column('balance', sa.Float(), nullable=True),
    sa.Column('equity', sa.Float(), nullable=True),
    sa.Column('margin', sa.Float(), nullable=True),
    sa.Column('margin_free', sa.Float(), nullable=True),
    sa.Column('margin_level', sa.Float(), nullable=True),
    sa.Column('daily_profit_target', sa.Float(), nullable=True),
    sa.Column('current_daily_profit', sa.Float(), nullable=True),
    sa.Column('profit_target_achieved', sa.Boolean(), nullable=True),
    sa.Column('predicted_profit', sa.Float(), nullable=True),
    sa.Column('predicted_direction', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_market_data_id'), 'market_data', ['id'], unique=False)
    op.create_index(op.f('ix_market_data_symbol'), 'market_data', ['symbol'], unique=False)
    op.create_index(op.f('ix_market_data_time'), 'market_data', ['time'], unique=False)
    op.alter_column('trades', 'ticket',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('trades', 'ticket',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.drop_index(op.f('ix_market_data_time'), table_name='market_data')
    op.drop_index(op.f('ix_market_data_symbol'), table_name='market_data')
    op.drop_index(op.f('ix_market_data_id'), table_name='market_data')
    op.drop_table('market_data')
    # ### end Alembic commands ###
